name: home-assistant-av-access-dev

services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: home-assistant
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
    ports:
      - "8124:8123"
    volumes:
      - ./config:/config:rw
      - ../custom_components/av_access:/config/custom_components/av_access:rw
