name: Ruff

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  ruff:
    name: Ruff
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.13"

      - name: Install Ruff
        run: pip install ruff==0.16.8

      - name: Lint with Ruff
        run: ruff check custom_components/

      - name: Check formatting with Ruff
        run: ruff format --check custom_components/
